project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  title: "BigFish"
  repo-url: https://github.com/fishsizeproject/BigFishGame
  navbar:
    pinned: true
    collapse: true
    left:
      - href: rules.qmd
        text: Rules
      - href: wildCards.qmd
        text: Wildcards
      - href: resources.qmd
        text: Resources
      - href: AboutDevs.qmd
        text: About Us
  sidebar:
  # id, title, search: true, tools, contents: "auto", style: "docked", background, foreground, border, alignment, collapse-level, pinned, header, footer
   - id: sidebar1
     title: "Sidebar-1"
     pinned: true
     contents: "auto"
     style: "docked"
  page-footer:
    left: |
      [![](/images/icons/envelope-solid.svg){fig-alt="info@fishsizeproject.org" fig-align="center" height="1.5em" fig-valign="top" margin-left="5px"}](mailto:info@fishsizeproject.org)
      [info@fishsizeproject.org](info@fishsizeproject.org)<br>
      [![](/images/icons/github.svg){fig-alt="info@fishsizeproject.org" fig-align="center" height="1.5em" fig-valign="top" margin-left="5px"}](mailto:info@fishsizeproject.org)
      [![](/images/icons/rss-solid.svg){fig-alt="info@fishsizeproject.org" fig-align="center" height="1.5em" fig-valign="top" margin-left="5px"}](mailto:info@fishsizeproject.org)
    right: |
      Copyright BigFish Project 2024.<br>
      This work is supported by a 2020 Pew Fellowship in Marine Conservation.<br>
    background: dark
    foreground: light

format:
  html:
    theme: lux
    page-layout: full
    grid:
      sidebar-width: 100px
      body-width: 900px
      margin-width: 100px
      gutter-width: 30px
    css: styles.css
    toc: true
    fig-responsive: true



