project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  title: "BigFish"
  repo-url: https://github.com/fishsizeproject/BigFishGame
  navbar:
    pinned: true
    collapse: true
    left:
      - href: rules.qmd
        text: Rules
      - href: wildCards.qmd
        text: Wildcards
      - href: resources.qmd
        text: Resources
      - href: AboutDevs.qmd
        text: About Us
  sidebar:
  # id, title, search: true, tools, contents: "auto", style: "docked", background, foreground, border, alignment, collapse-level, pinned, header, footer
   - id: sidebar1
     title: "Sidebar-1"
     pinned: true
     contents: "auto"
     style: "docked"
  page-footer:
    left: |
      <p style="font-size:10px color:#fffff"> Contact us at [info\@fishsizeproject.org](mailto:info@fishsizeproject.org "Contact email")</p>
    center: " "
    right: |
      <p style="color:#fffff">Copyright 2024, BigFish Project <br></p>
      [![](images/icons/github.svg){fig-alt="github" fig-align="right" width="3%" padding-left="5px"}](https://github.com/fishsizeproject/BigFishGame)
      [![](images/icons/rss-solid.svg){fig-alt="RSS" fig-align="right" width="3%" padding-left="5px"}](https://github.com/fishsizeproject/BigFishGame)
    background: dark

format:
  html:
    theme: lux
    page-layout: full
    grid:
      sidebar-width: 100px
      body-width: 900px
      margin-width: 100px
      gutter-width: 30px
    css: styles.css
    toc: true
    fig-responsive: true



