project:
  type: website
  output-dir: docs

website:
  title: "BigFish"
  navbar:
    left:
      - href: rules.qmd
        text: Rules
      - href: wildCards.qmd
        text: Wildcards
      - href: resources.qmd
        text: Resources
  #sidebar:
  #id, title, search: true, tools, contents: "auto", style: "docked", background, foreground, border, alignment, collapse-level, pinned, header, footer
  #  - id: sidebar1
  #    title: "Sidebar-1"
  #    pinned: true
  #    contents: "auto"
  #    style: "docked"
  page-footer:
    left: |
      <p font-size:10px> Contact us at [info@fishsizeproject.org](mailto:info@fishsizeproject.org)</p> ![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Contact email" width=65px}](mailto:info@fishsizeproject.org)
    center:
      - text: "Home"
        href: index.qmd
    right:
      - text: Copyright 2024, BigFish Project
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Blog RSS
    background: dark
    foreground: light

format:
  html:
    theme: lux
    page-layout: full
    grid:
      sidebar-width: 100px
      body-width: 900px
      margin-width: 100px
      gutter-width: 30px
    css: styles.css
    toc: true
    fig-responsive: true



